version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
  configuration: docs/conf.py

formats: all

python:
  version: 3.7
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt